import { SpeedInsights } from "@vercel/speed-insights/next"
import "../globals.css";
import Wireframe from "@/components/Wireframe";
import Header from "./Header";
import Footer from "./Footer";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayout = function({ children }) {
  return (
    <html lang="en">
      <Wireframe/>
      <head>
        <link rel="icon" href="/images/favicon.png"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        {/* <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&family=Salsa&display=swap" rel="stylesheet"/> */}
        <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&family=Salsa&family=Short+Stack&display=swap" rel="stylesheet"></link>
      </head>
      
      <body className="theme-default bg-primary">
        <Header/>
        
        {children}
      
        <Footer/>
        <SpeedInsights/>
      </body>
    </html>
  );
}

export default RootLayout;